#!/bin/bash
export PATH=/usr/local/bin:$PATH;

sudo yum -y update
sudo yum install -y docker
sudo service docker start
sudo usermod -a -G docker ec2-user
sudo chkconfig docker on
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
chown root:docker /usr/local/bin/docker-compose
chown ec2-user:ec2-user /home/ec2-user/app/docker-compose-simple.yml
/usr/local/bin/docker-compose -f /home/ec2-user/app/docker-compose-simple.yml build
/usr/local/bin/docker-compose -f /home/ec2-user/app/docker-compose-simple.yml up
